name: "Pull Request"

on:
  pull_request:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Basilisk
        uses: actions/checkout@v3
        with:
          repository: AVSLab/basilisk
          lfs: true
          path: basilisk
      - name: "Apt-get Update"
        run: sudo apt-get update
      - name: "Build Container Image"
        run: podman build -t basilisk-jupyterlabs -f basilisk-jupyterlabs.Containerfile .
